 services:

  # ── API Node.js — Steam, Twitch, TUNA ──
  steam-api:
    build: .
    #image: ghcr.io/noctablob/stream-noctablob:latest
    container_name: steam-api-server
    pull_policy: build
    ports:
      - "3000:3000"
    environment:
      - STEAM_API_KEY=${STEAM_API_KEY}
      - STEAM_ID=${STEAM_ID}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CHANNEL=${TWITCH_CHANNEL}
      - TWITCH_CHANNEL_ID=${TWITCH_CHANNEL_ID}
      - TWITCH_USER_TOKEN=${TWITCH_USER_TOKEN}
      - TWITCH_REFRESH_TOKEN=${TWITCH_REFRESH_TOKEN}
    volumes:
      - C:\Developpement\Stream-NoctaBlob\data\tuna_track.txt:/tuna/track.txt:ro
    restart: unless-stopped

  # ── Nginx — sert les fichiers HTML statiques ──
  steam-ui:
    image: nginx:alpine
    container_name: steam-api-ui
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped
